------------------------------------------------------------
-- Sprint 4 - Python + Oracle Integration
-- Descrição: Exclusão total das tabelas e sequences.
------------------------------------------------------------

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE T_HC_CONSULTA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE T_HC_MEDICO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE T_HC_PACIENTE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_T_HC_CONSULTA';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_T_HC_MEDICO';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_T_HC_PACIENTE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

