------------------------------------------------------------
-- Sprint 4 - Python + Oracle Integration
-- Descrição: Criação das tabelas, sequences e dados iniciais
------------------------------------------------------------

-- ===============================
-- LIMPEZA ANTES DE CRIAR
-- ===============================
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE T_HC_CONSULTA CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE T_HC_MEDICO CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE T_HC_PACIENTE CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_T_HC_CONSULTA';
   EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_T_HC_MEDICO';
   EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_T_HC_PACIENTE';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

------------------------------------------------------------
-- SEQUENCES
------------------------------------------------------------
CREATE SEQUENCE SQ_T_HC_PACIENTE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_T_HC_MEDICO   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_T_HC_CONSULTA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

------------------------------------------------------------
-- TABELAS
------------------------------------------------------------

CREATE TABLE T_HC_PACIENTE (
    ID_PACIENTE CHAR(5) PRIMARY KEY,
    NM_PACIENTE VARCHAR2(50) NOT NULL,
    NR_CPF VARCHAR2(15) NOT NULL,
    NR_RG VARCHAR2(13),
    NR_ALTURA NUMBER(4,2),
    NR_PESO NUMBER(5,2),
    DT_NASCIMENTO DATE,
    DS_ESCOLARIDADE VARCHAR2(50),
    DS_ESTADO_CIVIL VARCHAR2(50),
    DS_DESCRICAO VARCHAR2(100)
);

CREATE TABLE T_HC_MEDICO (
    ID_MEDICO CHAR(5) PRIMARY KEY,
    NM_MEDICO VARCHAR2(30) NOT NULL,
    NR_CRM VARCHAR2(15) NOT NULL  -- corrigido para comportar CRM-SP12345
);

CREATE TABLE T_HC_CONSULTA (
    ID_CONSULTA CHAR(5) PRIMARY KEY,
    DT_HR_CONSULTA DATE,
    DS_MODALIDADE VARCHAR2(20)
);

------------------------------------------------------------
-- DADOS INICIAIS
------------------------------------------------------------
-- PACIENTES
INSERT INTO T_HC_PACIENTE (ID_PACIENTE, NM_PACIENTE, NR_CPF, NR_RG, NR_ALTURA, NR_PESO, DT_NASCIMENTO, DS_ESCOLARIDADE, DS_ESTADO_CIVIL, DS_DESCRICAO)
VALUES (TO_CHAR(SQ_T_HC_PACIENTE.NEXTVAL), 'Maria Oliveira', '12345678901', '1234567', 1.68, 62.5, TO_DATE('1995-05-10', 'YYYY-MM-DD'), 'Ensino Superior', 'Solteira', 'Paciente com histórico de ansiedade leve');

INSERT INTO T_HC_PACIENTE (ID_PACIENTE, NM_PACIENTE, NR_CPF, NR_RG, NR_ALTURA, NR_PESO, DT_NASCIMENTO, DS_ESCOLARIDADE, DS_ESTADO_CIVIL, DS_DESCRICAO)
VALUES (TO_CHAR(SQ_T_HC_PACIENTE.NEXTVAL), 'João da Silva', '23456789012', '2233445', 1.80, 85.2, TO_DATE('1988-03-22', 'YYYY-MM-DD'), 'Ensino Médio', 'Casado', 'Paciente hipertenso sob controle');

INSERT INTO T_HC_PACIENTE (ID_PACIENTE, NM_PACIENTE, NR_CPF, NR_RG, NR_ALTURA, NR_PESO, DT_NASCIMENTO, DS_ESCOLARIDADE, DS_ESTADO_CIVIL, DS_DESCRICAO)
VALUES (TO_CHAR(SQ_T_HC_PACIENTE.NEXTVAL), 'Ana Souza', '34567890123', '3344556', 1.60, 55.0, TO_DATE('1999-09-09', 'YYYY-MM-DD'), 'Ensino Superior', 'Solteira', 'Paciente em acompanhamento psicológico');

-- MEDICOS
INSERT INTO T_HC_MEDICO (ID_MEDICO, NM_MEDICO, NR_CRM)
VALUES (TO_CHAR(SQ_T_HC_MEDICO.NEXTVAL), 'Dr. Lucas Almeida', 'CRM-12345');

INSERT INTO T_HC_MEDICO (ID_MEDICO, NM_MEDICO, NR_CRM)
VALUES (TO_CHAR(SQ_T_HC_MEDICO.NEXTVAL), 'Dra. Fernanda Costa', 'CRM-67890');

INSERT INTO T_HC_MEDICO (ID_MEDICO, NM_MEDICO, NR_CRM)
VALUES (TO_CHAR(SQ_T_HC_MEDICO.NEXTVAL), 'Dr. Rafael Gomes', 'CRM-11223');

-- CONSULTAS
INSERT INTO T_HC_CONSULTA (ID_CONSULTA, DT_HR_CONSULTA, DS_MODALIDADE)
VALUES (TO_CHAR(SQ_T_HC_CONSULTA.NEXTVAL), TO_DATE('2025-11-06 15:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Presencial');

INSERT INTO T_HC_CONSULTA (ID_CONSULTA, DT_HR_CONSULTA, DS_MODALIDADE)
VALUES (TO_CHAR(SQ_T_HC_CONSULTA.NEXTVAL), TO_DATE('2025-11-07 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Online');

INSERT INTO T_HC_CONSULTA (ID_CONSULTA, DT_HR_CONSULTA, DS_MODALIDADE)
VALUES (TO_CHAR(SQ_T_HC_CONSULTA.NEXTVAL), TO_DATE('2025-11-08 09:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'Presencial');

COMMIT;
